/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package serverside.kotlin.datastore

import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction
import org.jetbrains.exposed.sql.SchemaUtils.create
import org.jetbrains.exposed.sql.SchemaUtils.drop

import serverside.kotlin.models.Todos

class DatabaseManager {
  fun Connect() {
    // TODO .envファイルから読み込みをしたい

    Database.connect(
      "jdbc:postgresql://localhost:5432/dev-ktor",
      driver = "org.postgresql.Driver",
      user = "keijunkumagai",
      password = "password"
    )
  }

  fun CreateTable() {
    transaction {
      addLogger(StdOutSqlLogger)
      SchemaUtils.create(Todos)
    }
  }

  fun DropTable() {
    transaction {
      addLogger(StdOutSqlLogger)
      SchemaUtils.drop(Todos)
    }
  }
}

